name: Deploy Application

on:
  push:
    branches: [main]  # Specifies that this action runs on pushes to the main branch.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the type of machine to run the job on.

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the Node.js version.

    - name: Install dependencies
      run: npm install  # Installs dependencies defined in package.json.

    - name: Build
      run: npm run build  # Runs the build script defined in package.json.

    - name: Deploy
      run: npm run deploy  # Runs the deploy script defined in package.json.
      env:
        BIGQUERY_CREDENTIALS_PATH: ${{ secrets.BIGQUERY_CREDENTIALS_PATH }}  # Uses the BigQuery credentials from GitHub Secrets.
