name: Daily Script Execution

on:
  schedule:
    # Runs every day at 10:05pm UTC  
    - cron: '0 22 * * *'

jobs:
  run-scrapy-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Upload Data Directory
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: ./data/scraped

    - name: Run get_yc_data.py script
      env:
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
      run: |
        echo "${BIGQUERY_CREDENTIALS}" > credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
        python3 ./scripts/get_yc_data.py

    - name: Run get_yc_description.py script
      env:
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      run: |
        echo "${BIGQUERY_CREDENTIALS}" > credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
        python3 ./scripts/get_yc_description.py --api_key $ALPHAVANTAGE_API_KEY

    - name: Upload Data Directory
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: ./data/

    - name: Run get_local_data.py script
      env:
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
      run: |
        echo "${BIGQUERY_CREDENTIALS}" > credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
        python3 ./scripts/get_local_data.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull origin main 
        git add -A 
        git commit -m "Update data" || echo "No changes to commit"
        git push origin main 
